[data]
root_dir = data/kitti/tracking
det3d_name = voxel_rcnn_tta
det2d_name = spatial_embeddings
det2d_emb_name = BoT
seg_name = spatial_embeddings
seg_emb_name = BoT
det3d_save_name = voxel_tta_point_box

[tracking]
offline = True
score_thresh = 0.2
use_pose = False
use_lidar = True
use_inst = False
use_det2d = True
use_embed = False
min_corr_pts = 1
min_corr_iou = 0.1
t_miss = 13
t_miss_new = 3
; t_hit should be zero for online tracking
t_hit = 3
match_algorithm = HA
dis_thresh = 0.5
app_thresh = 0.5
ang_thresh = 0
ent_ex_score = 0.25
app_m = 0.9
p = 10
q = 2

[refinement]
merge = True
box_size_fusion = True
interp = True
smooth = True
interp_max_interval = 4
ignore_thresh = 0.35
score_thresh = 0
nms_thresh = 1
pred_len = 0
tau = 8

[visualization]
trajectory = False
det_noise = False
contradiction = False
interpolation = False